feat(tls): add TlsStream support
tikue/tarpc pull request #7
Opened 2017-01-08 20:56 UTC by compressed

Here's my attempt to add TLS support to tarpc. I had first started with two tls-specific client and server files, but that seemed like a bit too much duplication so I merged those changes into the existing client and server files. The changes are really quite small, despite the large diff. The main changes are for the server it needs to take in a `TlsAcceptor` and for the client it needs to take in the domain you want to connect to along with a `TlsConnector`; both of these tls types are provided by the `native-tls` crate, which I have re-exported.

I needed to do some `replace`ing in the `Cargo.toml` because the released version of `native-tls` doesn't have the macos tls-related functions exposed that I needed for testing. This will also give a superfluous warning when compiling without the tls feature (`package replacement is not used: ...`). Once there is a new native-tls release, we can get rid of that replace.

For the `service!` macro I was able to eliminate almost all of the duplication via some helper macros.

I was also able to re-use all the tests with just some minimal refactoring.

The examples currently won't build right now when the `tls` feature is specified. I was thinking we could use some conditional compilation there like I did in the tests as well. I'll work on that next.

Let me know what you think!

-----
Commit message below:

When `-- features tls` is specified for tarpc, RPC communication will
occur over a `TlsStream<TcpStream>` instead of a `TcpStream`.

The `service!` macro has been refactored to limit the amount of code
duplication between the non-tls and tls versions.

In addition, the client and server logic has also been refactored to
limit the amount of duplication between the two code paths.

The functional tests have been refactored to use a common set of
functions for constructing the client and server structs so that all
the tests are shared across non-tls and tls test runs.

2017-01-08 21:53 UTC, tikue commented
This is awesome, thanks so much! We'll start reviewing soon.

2017-01-09 02:10 UTC, tikue requested changes
From what I've read so far, this looks great! Some initial comments.

2017-01-09 02:10 UTC, tikue commented on Cargo.toml
> +"tokio-core:0.1.2" = { git = "https://github.com/tokio-rs/tokio-core" }
This was updated to 0.1.3.

2017-01-09 02:10 UTC, tikue commented on README.md
> +    let _server = HelloServer.listen(addr, acceptor);
I always intended there to be an additional config param for all the miscellaneous things one might want to tweak. This seems like a good time to introduce that. Also, in the config struct, could the tls acceptor be optional `Option<TlsAcceptor>`? I think we should allow the mixing of TLS and non-TLS services, which I believe isn't possible as this PR currently stands?

2017-01-09 02:10 UTC, tikue commented on README.md
> +    let _server = HelloServer.listen(addr, acceptor);
And I think the same should be applied to the client side, so maybe in the respective modules there could be `client::Config` and `server::Config`. Those modules could be made public.

2017-01-09 02:10 UTC, tikue commented on README.md
> +    HelloServer.listen_with(addr, core.handle(), acceptor).unwrap();
If we go with the config struct approach, the handle should become a field of that as well. Not sure what'd be better, to have one client config struct, or one for each of sync, futures.

2017-01-09 02:10 UTC, tikue commented on src/errors.rs
> +pub fn native2io(e: ::native_tls::Error) -> io::Error {
nit: prefer `native_to_io`

2017-01-09 02:20 UTC, tikue commented on src/server.rs
> +cfg_if! {
if the `tls_acceptor` arg is replaced with a config struct, then we can probably constrain the `cfg_if!` to a much smaller surface of the code. It's fine if the config struct is empty (for now) when tls isn't enabled.

2017-01-09 19:40 UTC, compressed commented on README.md
> +    let _server = HelloServer.listen(addr, acceptor);
Yep, you're right. It doesn't allow mixing TLS and non-TLS currently. That's what I was asking about on gitter before. However, I do think it's good to try to allow this.

I really like the idea of the `Config` structs for client and server. That change should then unify the API then across both stream types and I believe then we'd only need one version of the macro.

Let me give this a shot and see where I end up. Thinking about the client, I believe we'll need to add another generic parameter to indicate the stream type...

2017-01-19 21:38 UTC, compressed commented
Closing this one in place of a new one on `google/tarpc`.

2017-01-19 21:38 UTC, closed without merging